### ISSUE TITLE
Scaling?

### ISSUE THREAD

**Issue by username1565** [otuncelli/f5-steganography#6]
Is there possible to enable the scaling for Image, if embedding file larger than capacity?
I see when capacity calculating, then image saved as JPEG.
Is this possible to auto-resize image up to capacity, without saving previous small image?

Maybe to increase capacity can be added the random LSB noice to bitmap or source Image.
After JPEG compressing, this picture must to have more coefficients...

**Comment by otuncelli** [comment]
It might be possible but it would give a hint to an attacker about the message length. I have no idea. This  is just a direct port from the java version. I don't maintain anymore. Feel free to fork and add new features.
